dist: trusty
sudo: required
install: true
language: go
go:
  - 1.11.2
env:
  global:
    - GOARCH=amd64
before_install:
  - sleep 15
  - sudo apt-get install -y
  - sudo apt-get install -y curl
  - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
  - chmod 700 get_helm.sh
  - sudo ./get_helm.sh
script:
  - make deps
  - make all
