apiVersion: openebs.io/v1alpha1
kind: OpenEBSInstallTemplate
metadata:
  name: oebs
  namespace: openebs
spec:
  # Default values copied from <project_dir>/helm-charts/openebs/values.yaml
  # Default values for openebs.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.
  rbac:
  # Specifies whether RBAC resources should be created
    create: true
    pspEnabled: false
    kyvernoEnabled: false
  serviceAccount:
    create: true
    name: 'openebs-maya-operator'
  imagePullSecrets: [ ]
  release:
    version: 2.12.2
  legacy:
    enabled: true
  image:
    pullPolicy: IfNotPresent
    repository: ''
  apiserver:
    enabled: true
    image: openebs/m-apiserver
    imageTag: 2.12.2
    replicas: 1
    ports:
      externalPort: 5656
      internalPort: 5656
    sparse:
      enabled: 'false'
    nodeSelector: { }
    tolerations: [ ]
    affinity: { }
    healthCheck:
      initialDelaySeconds: 30
      periodSeconds: 60
    resources: { }
  defaultStorageConfig:
    enabled: 'true'
  varDirectoryPath:
    baseDir: '/var/openebs'
  provisioner:
    enabled: true
    image: openebs/openebs-k8s-provisioner
    imageTag: 2.12.2
    replicas: 1
    enableLeaderElection: true
    patchJivaNodeAffinity: enabled
    nodeSelector: { }
    tolerations: [ ]
    affinity: { }
    healthCheck:
      initialDelaySeconds: 30
      periodSeconds: 60
    resources: { }
  localprovisioner:
    enabled: true
    image: openebs/provisioner-localpv
    imageTag: 2.12.2
    replicas: 1
    enableLeaderElection: true
    enableDeviceClass: true
    enableHostpathClass: true
    basePath: '/var/openebs/local'
    waitForBDBindTimeoutRetryCount: '12'
    nodeSelector: { }
    tolerations: [ ]
    affinity: { }
    healthCheck:
      initialDelaySeconds: 30
      periodSeconds: 60
    resources: { }
  snapshotOperator:
    enabled: true
    controller:
      image: openebs/snapshot-controller
      imageTag: 2.12.2
      resources: { }
    provisioner:
      image: openebs/snapshot-provisioner
      imageTag: 2.12.2
      resources: { }
    replicas: 1
    enableLeaderElection: true
    upgradeStrategy: Recreate
    nodeSelector: { }
    tolerations: [ ]
    affinity: { }
    healthCheck:
      initialDelaySeconds: 30
      periodSeconds: 60
  ndm:
    enabled: true
    image: openebs/node-disk-manager
    imageTag: 1.6.1
    sparse:
      path: '/var/openebs/sparse'
      size: '10737418240'
      count: '0'
    filters:
      enableOsDiskExcludeFilter: true
      osDiskExcludePaths: '/,/etc/hosts,/boot'
      enableVendorFilter: true
      excludeVendors: 'CLOUDBYT,OpenEBS'
      enablePathFilter: true
      includePaths: ''
      excludePaths: '/dev/loop,/dev/fd0,/dev/sr0,/dev/ram,/dev/dm-,/dev/md,/dev/rbd,/dev/zd'
    probes:
      enableSeachest: false
    nodeSelector: { }
    tolerations: [ ]
    healthCheck:
      initialDelaySeconds: 30
      periodSeconds: 60
    resources: { }
  ndmOperator:
    enabled: true
    image: openebs/node-disk-operator
    imageTag: 1.6.1
    replicas: 1
    upgradeStrategy: Recreate
    nodeSelector: { }
    tolerations: [ ]
    healthCheck:
      initialDelaySeconds: 15
      periodSeconds: 20
    readinessCheck:
      initialDelaySeconds: 5
      periodSeconds: 10
    resources: { }
  ndmExporter:
    enabled: false
    image:
      registry:
      repository: openebs/node-disk-exporter
      pullPolicy: IfNotPresent
      tag: 1.6.1
    nodeExporter:
      name: ndm-node-exporter
      podLabels:
        name: openebs-ndm-node-exporter
      metricsPort: 9101
    clusterExporter:
      name: ndm-cluster-exporter
      podLabels:
        name: openebs-ndm-cluster-exporter
      metricsPort: 9100
  webhook:
    enabled: true
    image: openebs/admission-server
    imageTag: 2.12.2
    failurePolicy: Fail
    replicas: 1
    healthCheck:
      initialDelaySeconds: 30
      periodSeconds: 60
    nodeSelector: { }
    tolerations: [ ]
    affinity: { }
    hostNetwork: false
    resources: { }
  helper:
    image: openebs/linux-utils
    helperImageTag: 2.12.2
  featureGates:
    enabled: true
    GPTBasedUUID:
      enabled: true
      featureGateFlag: GPTBasedUUID
    APIService:
      enabled: false
      featureGateFlag: APIService
      address: 0.0.0.0:9115
    USeOSDisk:
      enabled: false
      featureGateFlag: UseOSDisk
    MountChangeDetection:
      enabled: false
      featureGateFlag: MountChangeDetection
  crd:
    enableInstall: true
  policies:
    monitoring:
      enabled: true
      image: openebs/m-exporter
      imageTag: 2.12.2
  analytics:
    enabled: true
    pingInterval: 24h
  jiva:
    image: openebs/jiva
    imageTag: 2.12.2
    replicas: 3
    defaultStoragePath: '/var/openebs'
    enabled: false
    openebsLocalpv:
      enabled: false
    localpv-provisioner:
      openebsNDM:
        enabled: false
  cstor:
    pool:
      image: openebs/cstor-pool
      imageTag: 2.12.2
    poolMgmt:
      image: openebs/cstor-pool-mgmt
      imageTag: 2.12.2
    target:
      image: openebs/cstor-istgt
      imageTag: 2.12.2
    volumeMgmt:
      image: openebs/cstor-volume-mgmt
      imageTag: 2.12.2
    enabled: false
    openebsNDM:
      enabled: false
  openebs-ndm:
    enabled: false
  localpv-provisioner:
    enabled: false
    openebsNDM:
      enabled: false
  zfs-localpv:
    enabled: false
  lvm-localpv:
    enabled: false
  nfs-provisioner:
    enabled: false
  cleanup:
    image:
      registry: ''
      repository: bitnami/kubectl
      tag: ''
      imagePullSecrets: [ ]
