apiVersion: openebs.io/v1alpha1
kind: OpenEBSInstallTemplate
metadata:
  name: oebs
  namespace: openebs
spec:
  # Default values copied from <project_dir>/helm-charts/openebs/values.yaml
  # Default values for openebs.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.
  rbac:
  # Specifies whether RBAC resources should be created
    create: true
    pspEnabled: false
    kyvernoEnabled: false
  serviceAccount:
    create: true
    name: ''
  release:
  # "openebs.io/version" label for control plane components
    version: 2.11.0
  legacy:
    enabled: true
  image:
    pullPolicy: IfNotPresent
    repository: ''
  apiserver:
    enabled: true
    image: quay.io/openebs/m-apiserver
    imageTag: 2.11.0
    replicas: 1
    ports:
      externalPort: 5656
      internalPort: 5656
    sparse:
      enabled: 'false'
    healthCheck:
      initialDelaySeconds: 30
      periodSeconds: 60
  defaultStorageConfig:
    enabled: 'true'
  varDirectoryPath:
    baseDir: "/var/openebs"
  provisioner:
    enabled: true
    image: quay.io/openebs/openebs-k8s-provisioner
    imageTag: 2.11.0
    replicas: 1
    enableLeaderElection: true
    patchJivaNodeAffinity: enabled
    healthCheck:
      initialDelaySeconds: 30
      periodSeconds: 60
  localprovisioner:
    enabled: true
    image: quay.io/openebs/provisioner-localpv
    imageTag: 2.11.1
    replicas: '1'
    basePath: "/var/openebs/local"
    enableLeaderElection: true
    healthCheck:
      initialDelaySeconds: '30'
      periodSeconds: '60'
  snapshotOperator:
    enabled: true
    controller:
      image: quay.io/openebs/snapshot-controller
      imageTag: 2.11.0
    provisioner:
      image: quay.io/openebs/snapshot-provisioner
      imageTag: 2.11.0
    replicas: 1
    enableLeaderElection: true
    upgradeStrategy: Recreate
    healthCheck:
      initialDelaySeconds: 30
      periodSeconds: 60
  ndm:
    enabled: true
    image: quay.io/openebs/node-disk-manager
    imageTag: 1.6.0
    sparse:
      path: "/var/openebs/sparse"
      size: '10737418240'
      count: '0'
    filters:
      enableOsDiskExcludeFilter: true
      osDiskExcludePaths: "/,/etc/hosts,/boot"
      enableVendorFilter: 'true'
      excludeVendors: CLOUDBYT,OpenEBS
      enablePathFilter: true
      includePaths: ''
      excludePaths: "/dev/loop,/dev/fd0,/dev/sr0,/dev/ram,/dev/dm-,/dev/md,/dev/rbd,/dev/zd"
    probes:
      enableSeachest: false
    healthCheck:
      initialDelaySeconds: 30
      periodSeconds: 60
  ndmOperator:
    image: quay.io/openebs/node-disk-operator
    imageTag: 1.6.0
    replicas: 1
    upgradeStrategy: Recreate
    healthCheck:
      initialDelaySeconds: 15
      periodSeconds: 20
    readinessCheck:
      initialDelaySeconds: 5
      periodSeconds: 20
  webhook:
    enabled: true
    image: quay.io/openebs/admission-server
    imageTag: 2.11.0
    failurePolicy: Fail
    replicas: 1
    healthCheck:
      initialDelaySeconds: 30
      periodSeconds: 60
    hostNetwork: false
  helper:
    image: quay.io/openebs/linux-utils
    helperImageTag: 2.11.0
  featureGates:
    enabled: true
    GPTBasedUUID:
      enabled: true
      featureGateFlag: GPTBasedUUID
    APIService:
      enabled: false
      featureGateFlag: APIService
      address: 0.0.0.0:9115
    USeOSDisk:
      enabled: false
      featureGateFlag: UseOSDisk
    MountChangeDetection:
      enabled: false
      featureGateFlag: MountChangeDetection
  crd:
    enableInstall: true
  policies:
    monitoring:
      enabled: true
      image: quay.io/openebs/m-exporter
      imageTag: 2.11.0
  analytics:
    enabled: true
    pingInterval: 24h
  jiva:
    image: quay.io/openebs/jiva
    imageTag: 2.11.0
    replicas: 3
    defaultStoragePath: "/var/openebs"
    enabled: false
    openebsLocalpv:
      enabled: false
    localpv-provisioner:
      openebsNDM:
        enabled: false
  cstor:
    pool:
      image: quay.io/openebs/cstor-pool
      imageTag: 2.11.0
    poolMgmt:
      image: quay.io/openebs/cstor-pool-mgmt
      imageTag: 2.11.0
    target:
      image: quay.io/openebs/cstor-istgt
      imageTag: 2.11.0
    volumeMgmt:
      image: quay.io/openebs/cstor-volume-mgmt
      imageTag: 2.11.0
    enabled: false
    openebsNDM:
      enabled: false
  openebs-ndm:
    enabled: false
  localpv-provisioner:
    enabled: false
    openebsNDM:
      enabled: false
  zfs-localpv:
    enabled: false
  lvm-localpv:
    enabled: false

